FROM sonarqube:latest

#RUN cd ~
#RUN cd /opt/sonarqube \
#    && wget https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-9.0/sonar-l10n-zh-plugin-9.0.jar \
#    && mkdir extensions/plugins
#RUN cp sonar-l10n-zh-plugin-9.0.jar extensions/plugins \
#    && rm -rf sonar-l10n-zh-plugin-9.0.jar